spring:
  datasource:
    url: jdbc:mysql://192.168.85.123:3306/local_test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  session:
    store-type: redis
  http:
    encoding:
      force: true
  redis:
    host: 192.168.85.123
    port: 6379
    password: 123456
#security:
#  basic:
#    enabled: false
server:
  port: 8021
  session:
    timeout: 600
jy:
  security:
    browser:
#      loginPage: /demo-signIn.html
      loginType: REDIRECT
    code:
      image:
        length: 6
    oauth2:
      client:
        - {clientId: jy,clientSecret: jysecret,accessTokenValiditySeconds: 7200}



